
name: 'custom_postgres'
version: '1.0.0'
config-version: 2

profile: 'custom_postgres'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
models:
  custom_postgres:
    example:
      +materialized: table