services:
  source_postgres:
    image: postgres:15
    ports:
      - 5432:5433
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: hassaan
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - 5434:5435
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: hassaan
      POSTGRES_PASSWORD: secret

  elt_script:
    build:
      context: ./elt_script
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge